### ISSUE TITLE
Change the black-box CNN so that it outputs a confidence score in [0,1]

### ISSUE THREAD

**Issue by dj3500** [kirtanp/Road-Segmentation#6]

**Comment by kirtanp** [comment]
A not too complicated RandomForestClassifier which is much simpler than the provided CNN is alos giving an accuracy of 75%, so I am using that instead to get the points. Using a CNN just to get the high confidence points seems like an overkill.

**Comment by dj3500** [comment]
Oh, okay, cool.

**Comment by kirtanp** [comment]
Done by @dj3500
