### ISSUE TITLE
Prediction takes 10G RAM

### ISSUE THREAD

**Issue by dj3500** [kirtanp/Road-Segmentation#7]
So they can say that even prediction is not "really" reproducible. Investigate whether just reducing batch size would alleviate that.

**Comment by dj3500** [comment]
Indeed it does. (The duration is awful however, 20 minutes per image on a regular laptop.)

**Comment by minaahmed** [comment]
@kirtanp Hello, I get this error when I am trying to train the model on different dataset 

ValueError: Error when checking target: expected conv2d_24 to have shape (None, 512, 512, 1) but got array with shape (2, 512, 512, 3)
